package utils

// Version is set by build variable
var Version string

// Commit is the latest commit
var Commit string

// GetVersion returns the version set by the build variable reads the PCE information from the JSON generated by the login command
func GetVersion() string {
	return Version
}

// GetCommit returns the latest commit set by the build variable
func GetCommit() string {
	return Commit
}
